apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cxp-hello-k8s
  labels:
    app.kubernetes.io/name: cxp-hello-k8s
    helm.sh/chart: cxp-hello-k8s-0.8.0
    app.kubernetes.io/instance: cxp-hello-k8s
    app.kubernetes.io/managed-by: Helm
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cxp-hello-k8s
      app.kubernetes.io/instance: cxp-hello-k8s
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
